### ISSUE TITLE
EPIC - As a teacher I want to watch students’ code update in real time

### ISSUE THREAD

**Issue by gmccune22** [UFWebApps2-0/onyx-project02-11c#2]
**Acceptance criteria**
- [x] display in psuedo real-time the code replay of the project students are actively working on 
- [ ] send notification or display an indicator over the student if nothing has changed in 5 mins
- [ ] refresh screen of each student independently when their workspace auto-saves, compiles, and/or loads program to the arduino
- [ ] allow screens on dashboard to be reorganizable so that the teacher can make the layout match the seating arrangement or alphabetical or custom set a watch on particular students

**Tasks**

- [x] Break this epic up into smaller user stories, esp. 3d acceptance criteria
- [ ] create a list of students that have active sessions for this particular classroom
- [ ] create a service to grab most recent code replays for students, as a group or individually
- [ ] create a service to indicate when a code replay has been updated so that it triggers and update on the interface
- [ ] client-side have a listener waiting to update the dashboards when changes occur
- [ ] passive notification- client-side a method runs to indicate if the code has changed in a 5 min period. 
- [ ] active notification - teacher sets a watch on particular students
