### ISSUE TITLE
As a teacher I want to chosen a student to serve as a helper for other students.

### ISSUE THREAD

**Issue by gmccune22** [UFWebApps2-0/onyx-project02-11c#3]
**Acceptance criteria**

- [ ] teacher is able to select 1 or more students from the list of students in the class  (roster) to serve as a helper
- [ ] students should be listed as available only if they have an active session during the period

**Tasks**

- [ ] pull a list of students in the class
- [ ] active notification - teacher sets a watch on particular students
